-- MySQL Script generated by MySQL Workbench
-- 09/09/16 14:08:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema healthcontrol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema healthcontrol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `healthcontrol` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `healthcontrol` ;

-- -----------------------------------------------------
-- Table `healthcontrol`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `healthcontrol`.`devices` (
  `idDevice` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `mac` VARCHAR(17) NULL COMMENT '',
  PRIMARY KEY (`idDevice`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `healthcontrol`.`sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `healthcontrol`.`sensors` (
  `idSensor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idSensor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `healthcontrol`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `healthcontrol`.`data` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idSensor` INT NOT NULL COMMENT '',
  `idDevice` INT NOT NULL COMMENT '',
  `value` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_data_sensors_idx` (`idSensor` ASC)  COMMENT '',
  INDEX `fk_data_devices1_idx` (`idDevice` ASC)  COMMENT '',
  CONSTRAINT `fk_data_sensors`
    FOREIGN KEY (`idSensor`)
    REFERENCES `healthcontrol`.`sensors` (`idSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_devices1`
    FOREIGN KEY (`idDevice`)
    REFERENCES `healthcontrol`.`devices` (`idDevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
