/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './device';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar';
import * as import13 from 'ionic-angular/components/navbar/navbar';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from 'ionic-angular/components/menu/menu-toggle';
import * as import17 from 'ionic-angular/components/icon/icon';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from 'ionic-angular/components/content/content';
import * as import20 from 'ionic-angular/components/list/list';
import * as import21 from 'ionic-angular/components/label/label';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from 'ionic-angular/components/spinner/spinner';
import * as import37 from '../../node_modules/ionic-angular/components/spinner/spinner.ngfactory';
var renderType_Device_Host:import0.RenderComponentType = (null as any);
class _View_Device_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Device_0_4:import3.Device;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Device_Host0,renderType_Device_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-device',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Device0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Device_0_4 = new import3.Device(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams));
    this._appEl_0.initComponent(this._Device_0_4,[],compView_0);
    compView_0.create(this._Device_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Device) && (0 === requestNodeIndex))) { return this._Device_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Device_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Device_Host === (null as any))) { (renderType_Device_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_Device_Host0(viewUtils,parentInjector,declarationEl);
}
export const DeviceNgFactory:import11.ComponentFactory<import3.Device> = new import11.ComponentFactory<import3.Device>('page-device',viewFactory_Device_Host0,import3.Device);
const styles_Device:any[] = [];
var renderType_Device:import0.RenderComponentType = (null as any);
class _View_Device0 extends import1.AppView<import3.Device> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import13.Navbar;
  _text_4:any;
  _el_5:any;
  _ToolbarItem_5_3:import14.ToolbarItem;
  _query_Button_5_0:import15.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _MenuToggle_7_3:import16.MenuToggle;
  _ToolbarItem_7_4:import14.ToolbarItem;
  _query_Button_7_0:import15.QueryList<any>;
  _text_8:any;
  _el_9:any;
  _Icon_9_3:import17.Icon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _ToolbarTitle_13_4:import18.ToolbarTitle;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Content_18_4:import19.Content;
  _text_19:any;
  _el_20:any;
  _List_20_3:import20.List;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import21.Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _Label_25_3:import21.Label;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _Label_28_3:import21.Label;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _anchor_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _TemplateRef_38_5:any;
  _NgIf_38_6:import22.NgIf;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Device0,renderType_Device,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import26.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_5,'left','');
    this.renderer.setElementAttribute(this._el_5,'start','');
    this._ToolbarItem_5_3 = new import14.ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_5_0 = new import15.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'menuToggle','');
    this._MenuToggle_7_3 = new import16.MenuToggle(this.parentInjector.get(import28.MenuController),new import24.ElementRef(this._el_7),this.parentInjector.get(import25.ViewController,(null as any)),this._Navbar_3_4);
    this._ToolbarItem_7_4 = new import14.ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_7_0 = new import15.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_9,'name','menu');
    this.renderer.setElementAttribute(this._el_9,'role','img');
    this._Icon_9_3 = new import17.Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_13 = new import2.AppElement(13,3,this,this._el_13);
    var compView_13:any = import29.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(13),this._appEl_13);
    this._ToolbarTitle_13_4 = new import18.ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_13.initComponent(this._ToolbarTitle_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'',(null as any));
    compView_13.create(this._ToolbarTitle_13_4,[[].concat([this._text_14])],(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      [].concat([this._el_5]),
      [],
      [],
      [].concat([
        this._text_4,
        this._text_12,
        this._el_13,
        this._text_15
      ]
      )
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_18 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_18,'padding','');
    this._appEl_18 = new import2.AppElement(18,(null as any),this,this._el_18);
    var compView_18:any = import30.viewFactory_Content0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Content_18_4 = new import19.Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_18.initComponent(this._Content_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_20_3 = new import20.List(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import34.GestureController));
    this._text_21 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-label',(null as any));
    this._Label_22_3 = new import21.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_22),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_20,'ion-label',(null as any));
    this._Label_25_3 = new import21.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_25),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_20,'ion-label',(null as any));
    this._Label_28_3 = new import21.Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_28),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_20,'\n  ',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','valueBPM');
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'button',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Ler valor BPM',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_38 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_38 = new import2.AppElement(38,18,this,this._anchor_38);
    this._TemplateRef_38_5 = new import35.TemplateRef_(this._appEl_38,viewFactory_Device1);
    this._NgIf_38_6 = new import22.NgIf(this._appEl_38.vcRef,this._TemplateRef_38_5);
    this._text_39 = this.renderer.createText((null as any),'\n',(null as any));
    compView_18.create(this._Content_18_4,[
      [],
      [].concat([
        this._text_19,
        this._el_20,
        this._text_31,
        this._el_32,
        this._text_34,
        this._el_35,
        this._text_37,
        this._appEl_38,
        this._text_39
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._anchor_38,
      this._text_39,
      this._text_40
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.Icon) && (9 === requestNodeIndex))) { return this._Icon_9_3; }
    if (((token === import16.MenuToggle) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MenuToggle_7_3; }
    if (((token === import14.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarItem_7_4; }
    if (((token === import14.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_5_3; }
    if (((token === import18.ToolbarTitle) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ToolbarTitle_13_4; }
    if (((token === import13.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Navbar_3_4; }
    if (((token === import12.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Header_1_3; }
    if (((token === import21.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3; }
    if (((token === import21.Label) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Label_25_3; }
    if (((token === import21.Label) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Label_28_3; }
    if (((token === import20.List) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._List_20_3; }
    if (((token === import35.TemplateRef) && (38 === requestNodeIndex))) { return this._TemplateRef_38_5; }
    if (((token === import22.NgIf) && (38 === requestNodeIndex))) { return this._NgIf_38_6; }
    if (((token === import19.Content) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Content_18_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_7_3.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_9_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_18_4.ngOnInit(); }
    const currVal_14:any = this.context.isScanning;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgIf_38_6.ngIf = currVal_14;
      this._expr_14 = currVal_14;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
        this._query_Button_7_0.reset([]);
        this._ToolbarItem_7_4._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([]);
        this._ToolbarItem_5_3._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
    }
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_7_3.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_7,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_9_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_9,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'\n      Dispositivo ',this.context.device.name,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_14,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_18_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_18,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.device.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_23,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(1,'',this.context.device.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_26,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import4.interpolate(1,'',this.context.device.address,'');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_29,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import4.interpolate(1,'\n    Valor batimento: ',this.context.valueBPM,'\n  ');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_33,currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_9_3.ngOnDestroy();
    this._Content_18_4.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_7_3.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.scan()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Device0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Device> {
  if ((renderType_Device === (null as any))) { (renderType_Device = viewUtils.createRenderComponentType('/home/davikawasaki/GitHub/healthcontrol/ionic/healthControl/.tmp/pages/device/device.html',0,import10.ViewEncapsulation.None,styles_Device,{})); }
  return new _View_Device0(viewUtils,parentInjector,declarationEl);
}
class _View_Device1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Spinner_0_4:import36.Spinner;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Device1,renderType_Device,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-spinner',(null as any));
    this.renderer.setElementAttribute(this._el_0,'name','circles');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import37.viewFactory_Spinner0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Spinner_0_4 = new import36.Spinner(this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Spinner_0_4,[],compView_0);
    compView_0.create(this._Spinner_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.Spinner) && (0 === requestNodeIndex))) { return this._Spinner_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_0:any = 'circles';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Spinner_0_4.name = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Spinner_0_4.paused;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'spinner-paused',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Device1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Device1(viewUtils,parentInjector,declarationEl);
}