/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './bluetooth';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../services/DeviceService';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/navbar/navbar';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from 'ionic-angular/components/menu/menu-toggle';
import * as import18 from 'ionic-angular/components/icon/icon';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/content/content';
import * as import21 from 'ionic-angular/components/grid/grid';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from 'ionic-angular/components/list/list';
import * as import24 from '@angular/common/src/directives/ng_for';
import * as import25 from 'ionic-angular/components/button/button';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/components/menu/menu-controller';
import * as import32 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import33 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from '@angular/core/src/linker/template_ref';
import * as import38 from 'ionic-angular/gestures/gesture-controller';
import * as import39 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import40 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import41 from 'ionic-angular/components/spinner/spinner';
import * as import42 from '../../node_modules/ionic-angular/components/spinner/spinner.ngfactory';
import * as import43 from 'ionic-angular/components/item/item';
import * as import44 from 'ionic-angular/components/label/label';
import * as import45 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import46 from 'ionic-angular/util/form';
var renderType_Bluetooth_Host:import0.RenderComponentType = (null as any);
class _View_Bluetooth_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Bluetooth_0_4:import3.Bluetooth;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Bluetooth_Host0,renderType_Bluetooth_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-bluetooth',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Bluetooth0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Bluetooth_0_4 = new import3.Bluetooth(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.DeviceService));
    this._appEl_0.initComponent(this._Bluetooth_0_4,[],compView_0);
    compView_0.create(this._Bluetooth_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Bluetooth) && (0 === requestNodeIndex))) { return this._Bluetooth_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Bluetooth_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Bluetooth_Host === (null as any))) { (renderType_Bluetooth_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_Bluetooth_Host0(viewUtils,parentInjector,declarationEl);
}
export const BluetoothNgFactory:import12.ComponentFactory<import3.Bluetooth> = new import12.ComponentFactory<import3.Bluetooth>('page-bluetooth',viewFactory_Bluetooth_Host0,import3.Bluetooth);
const styles_Bluetooth:any[] = [];
var renderType_Bluetooth:import0.RenderComponentType = (null as any);
class _View_Bluetooth0 extends import1.AppView<import3.Bluetooth> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import13.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import14.Navbar;
  _text_4:any;
  _el_5:any;
  _ToolbarItem_5_3:import15.ToolbarItem;
  _query_Button_5_0:import16.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _MenuToggle_7_3:import17.MenuToggle;
  _ToolbarItem_7_4:import15.ToolbarItem;
  _query_Button_7_0:import16.QueryList<any>;
  _text_8:any;
  _el_9:any;
  _Icon_9_3:import18.Icon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _ToolbarTitle_13_4:import19.ToolbarTitle;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Content_18_4:import20.Content;
  _text_19:any;
  _el_20:any;
  _Row_20_3:import21.Row;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgIf_22_6:import22.NgIf;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _List_25_3:import23.List;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import24.NgFor;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _Button_30_4:import25.Button;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Bluetooth0,renderType_Bluetooth,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import13.Header(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import28.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import29.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import14.Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_5,'left','');
    this.renderer.setElementAttribute(this._el_5,'start','');
    this._ToolbarItem_5_3 = new import15.ToolbarItem(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_5_0 = new import16.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'menuToggle','');
    this._MenuToggle_7_3 = new import17.MenuToggle(this.parentInjector.get(import31.MenuController),new import27.ElementRef(this._el_7),this.parentInjector.get(import28.ViewController,(null as any)),this._Navbar_3_4);
    this._ToolbarItem_7_4 = new import15.ToolbarItem(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_7_0 = new import16.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_9,'name','menu');
    this.renderer.setElementAttribute(this._el_9,'role','img');
    this._Icon_9_3 = new import18.Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_13 = new import2.AppElement(13,3,this,this._el_13);
    var compView_13:any = import32.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(13),this._appEl_13);
    this._ToolbarTitle_13_4 = new import19.ToolbarTitle(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_13.initComponent(this._ToolbarTitle_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n      Dispositivos Bluetooth\n    ',(null as any));
    compView_13.create(this._ToolbarTitle_13_4,[[].concat([this._text_14])],(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      [].concat([this._el_5]),
      [],
      [],
      [].concat([
        this._text_4,
        this._text_12,
        this._el_13,
        this._text_15
      ]
      )
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_18 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_18,'padding','');
    this._appEl_18 = new import2.AppElement(18,(null as any),this,this._el_18);
    var compView_18:any = import33.viewFactory_Content0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Content_18_4 = new import20.Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_18.initComponent(this._Content_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','display-flex center');
    this._Row_20_3 = new import21.Row();
    this._text_21 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import37.TemplateRef_(this._appEl_22,viewFactory_Bluetooth1);
    this._NgIf_22_6 = new import22.NgIf(this._appEl_22.vcRef,this._TemplateRef_22_5);
    this._text_23 = this.renderer.createText(this._el_20,'\n  ',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_25,'inset','');
    this._List_25_3 = new import23.List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_25),this.renderer,this.parentInjector.get(import38.GestureController));
    this._text_26 = this.renderer.createText(this._el_25,'\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._appEl_27 = new import2.AppElement(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import37.TemplateRef_(this._appEl_27,viewFactory_Bluetooth2);
    this._NgFor_27_6 = new import24.NgFor(this._appEl_27.vcRef,this._TemplateRef_27_5,this.parentInjector.get(import39.IterableDiffers),this.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n  ',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_30,'block','');
    this.renderer.setElementAttribute(this._el_30,'ion-button','');
    this.renderer.setElementAttribute(this._el_30,'style','position:absolute;bottom:15px;right:0');
    this._appEl_30 = new import2.AppElement(30,18,this,this._el_30);
    var compView_30:any = import40.viewFactory_Button0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Button_30_4 = new import25.Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_30),this.renderer);
    this._appEl_30.initComponent(this._Button_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'',(null as any));
    compView_30.create(this._Button_30_4,[[].concat([this._text_31])],(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n',(null as any));
    compView_18.create(this._Content_18_4,[
      [],
      [].concat([
        this._text_19,
        this._el_20,
        this._text_24,
        this._el_25,
        this._text_29,
        this._el_30,
        this._text_32
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Icon) && (9 === requestNodeIndex))) { return this._Icon_9_3; }
    if (((token === import17.MenuToggle) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MenuToggle_7_3; }
    if (((token === import15.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarItem_7_4; }
    if (((token === import15.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_5_3; }
    if (((token === import19.ToolbarTitle) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ToolbarTitle_13_4; }
    if (((token === import14.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Navbar_3_4; }
    if (((token === import13.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Header_1_3; }
    if (((token === import37.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import22.NgIf) && (22 === requestNodeIndex))) { return this._NgIf_22_6; }
    if (((token === import21.Row) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Row_20_3; }
    if (((token === import37.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import24.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6; }
    if (((token === import23.List) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._List_25_3; }
    if (((token === import25.Button) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Button_30_4; }
    if (((token === import20.Content) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Content_18_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_7_3.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_9_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_18_4.ngOnInit(); }
    const currVal_8:any = this.context.isScanning;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_22_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    changes = (null as any);
    const currVal_9:any = this.context.devicesList;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgFor_27_6.ngForOf = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgFor_27_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_27_6.ngDoCheck(); }
    changed = false;
    const currVal_11:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Button_30_4.block = currVal_11;
      changed = true;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import4.interpolate(1,'',this.context.color,'');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Button_30_4.color = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    if (changed) { this._appEl_30.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
        this._query_Button_7_0.reset([]);
        this._ToolbarItem_7_4._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([]);
        this._ToolbarItem_5_3._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_30_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_7_3.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_7,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_9_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_9,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_18_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_18,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_13:any = import4.interpolate(1,'',this.context.scan,'');
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setText(this._text_31,currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_9_3.ngOnDestroy();
    this._Content_18_4.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_7_3.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.startScanning()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Bluetooth0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Bluetooth> {
  if ((renderType_Bluetooth === (null as any))) { (renderType_Bluetooth = viewUtils.createRenderComponentType('/home/davikawasaki/GitHub/healthcontrol/ionic/healthControl/.tmp/pages/bluetooth/bluetooth.html',0,import11.ViewEncapsulation.None,styles_Bluetooth,{})); }
  return new _View_Bluetooth0(viewUtils,parentInjector,declarationEl);
}
class _View_Bluetooth1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Spinner_0_4:import41.Spinner;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Bluetooth1,renderType_Bluetooth,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-spinner',(null as any));
    this.renderer.setElementAttribute(this._el_0,'name','circles');
    this.renderer.setElementAttribute(this._el_0,'style','font-size: 5em;');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import42.viewFactory_Spinner0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Spinner_0_4 = new import41.Spinner(this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Spinner_0_4,[],compView_0);
    compView_0.create(this._Spinner_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Spinner) && (0 === requestNodeIndex))) { return this._Spinner_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_0:any = 'circles';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Spinner_0_4.name = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Spinner_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Spinner_0_4.paused;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'spinner-paused',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Bluetooth1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Bluetooth1(viewUtils,parentInjector,declarationEl);
}
class _View_Bluetooth2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import43.Item;
  _ItemContent_2_5:import43.ItemContent;
  _query_Label_2_0:import16.QueryList<any>;
  _query_Button_2_1:import16.QueryList<any>;
  _query_Icon_2_2:import16.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Label_4_3:import44.Label;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _Label_7_3:import44.Label;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Bluetooth2,renderType_Bluetooth,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import45.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import43.Item(this.parent.parentInjector.get(import46.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import43.ItemContent();
    this._query_Label_2_0 = new import16.QueryList<any>();
    this._query_Button_2_1 = new import16.QueryList<any>();
    this._query_Icon_2_2 = new import16.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_4_3 = new import44.Label(this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_4),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_7_3 = new import44.Label(this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_7),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_2_0.reset([
      this._Label_4_3,
      this._Label_7_3
    ]
    );
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [],
      [].concat([
        this._el_4,
        this._el_7
      ]
      ),
      [].concat([
        this._text_3,
        this._text_6,
        this._text_9,
        this._text_10,
        this._text_11
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.Label) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Label_4_3; }
    if (((token === import44.Label) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Label_7_3; }
    if (((token === import43.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Item_2_4; }
    if (((token === import43.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ItemContent_2_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.connectToDevice(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Bluetooth2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Bluetooth2(viewUtils,parentInjector,declarationEl);
}