/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './historico';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from 'ionic-angular/components/menu/menu-toggle';
import * as import16 from 'ionic-angular/components/icon/icon';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/components/list/list';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/navigation/view-controller';
import * as import24 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/components/menu/menu-controller';
import * as import27 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from 'ionic-angular/gestures/gesture-controller';
import * as import33 from '@angular/core/src/linker/template_ref';
import * as import34 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import35 from 'ionic-angular/components/item/item';
import * as import36 from 'ionic-angular/components/label/label';
import * as import37 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import38 from 'ionic-angular/util/form';
var renderType_Historico_Host:import0.RenderComponentType = (null as any);
class _View_Historico_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Historico_0_4:import3.Historico;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Historico_Host0,renderType_Historico_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-historico',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Historico0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Historico_0_4 = new import3.Historico(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._Historico_0_4,[],compView_0);
    compView_0.create(this._Historico_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Historico) && (0 === requestNodeIndex))) { return this._Historico_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Historico_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Historico_Host === (null as any))) { (renderType_Historico_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_Historico_Host0(viewUtils,parentInjector,declarationEl);
}
export const HistoricoNgFactory:import10.ComponentFactory<import3.Historico> = new import10.ComponentFactory<import3.Historico>('page-historico',viewFactory_Historico_Host0,import3.Historico);
const styles_Historico:any[] = [];
var renderType_Historico:import0.RenderComponentType = (null as any);
class _View_Historico0 extends import1.AppView<import3.Historico> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  _ToolbarItem_4_3:import13.ToolbarItem;
  _query_Button_4_0:import14.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _MenuToggle_6_3:import15.MenuToggle;
  _ToolbarItem_6_4:import13.ToolbarItem;
  _query_Button_6_0:import14.QueryList<any>;
  _text_7:any;
  _el_8:any;
  _Icon_8_3:import16.Icon;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _ToolbarTitle_12_4:import17.ToolbarTitle;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Content_17_4:import18.Content;
  _text_18:any;
  _el_19:any;
  _List_19_3:import19.List;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import20.NgFor;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Historico0,renderType_Historico,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import23.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import24.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import25.App),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_4,'left','');
    this.renderer.setElementAttribute(this._el_4,'start','');
    this._ToolbarItem_4_3 = new import13.ToolbarItem(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import14.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'menuToggle','');
    this._MenuToggle_6_3 = new import15.MenuToggle(this.parentInjector.get(import26.MenuController),new import22.ElementRef(this._el_6),this.parentInjector.get(import23.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_6_4 = new import13.ToolbarItem(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_6_0 = new import14.QueryList<any>();
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_8,'name','menu');
    this.renderer.setElementAttribute(this._el_8,'role','img');
    this._Icon_8_3 = new import16.Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_12 = new import2.AppElement(12,2,this,this._el_12);
    var compView_12:any = import27.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(12),this._appEl_12);
    this._ToolbarTitle_12_4 = new import17.ToolbarTitle(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_12.initComponent(this._ToolbarTitle_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'Histórico',(null as any));
    compView_12.create(this._ToolbarTitle_12_4,[[].concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_17,'padding','');
    this._appEl_17 = new import2.AppElement(17,(null as any),this,this._el_17);
    var compView_17:any = import28.viewFactory_Content0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Content_17_4 = new import18.Content(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_17.initComponent(this._Content_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n\n   ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_19_3 = new import19.List(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import32.GestureController));
    this._text_20 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_21 = new import2.AppElement(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import33.TemplateRef_(this._appEl_21,viewFactory_Historico1);
    this._NgFor_21_6 = new import20.NgFor(this._appEl_21.vcRef,this._TemplateRef_21_5,this.parentInjector.get(import34.IterableDiffers),this.ref);
    this._text_22 = this.renderer.createText(this._el_19,'\n  ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    compView_17.create(this._Content_17_4,[
      [],
      [].concat([
        this._text_18,
        this._el_19,
        this._text_23
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._text_24
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.Icon) && (8 === requestNodeIndex))) { return this._Icon_8_3; }
    if (((token === import15.MenuToggle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MenuToggle_6_3; }
    if (((token === import13.ToolbarItem) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarItem_6_4; }
    if (((token === import13.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarItem_4_3; }
    if (((token === import17.ToolbarTitle) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarTitle_12_4; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Header_0_3; }
    if (((token === import33.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import20.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6; }
    if (((token === import19.List) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._List_19_3; }
    if (((token === import18.Content) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Content_17_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_6_3.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_8_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_17_4.ngOnInit(); }
    changes = (null as any);
    const currVal_8:any = this.context.listaHistorico;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgFor_21_6.ngForOf = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._NgFor_21_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_21_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_0.dirty) {
        this._query_Button_6_0.reset([]);
        this._ToolbarItem_6_4._buttons = this._query_Button_6_0;
        this._query_Button_6_0.notifyOnChanges();
      }
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([]);
        this._ToolbarItem_4_3._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_6_3.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_6,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_8_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_8,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_17_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_8_3.ngOnDestroy();
    this._Content_17_4.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_6_3.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Historico0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Historico> {
  if ((renderType_Historico === (null as any))) { (renderType_Historico = viewUtils.createRenderComponentType('/home/davikawasaki/GitHub/healthcontrol/ionic/healthControl/.tmp/pages/historico/historico.html',0,import9.ViewEncapsulation.None,styles_Historico,{})); }
  return new _View_Historico0(viewUtils,parentInjector,declarationEl);
}
class _View_Historico1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import35.Item;
  _ItemContent_0_5:import35.ItemContent;
  _query_Label_0_0:import14.QueryList<any>;
  _query_Button_0_1:import14.QueryList<any>;
  _query_Icon_0_2:import14.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import36.Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _Label_5_3:import36.Label;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Historico1,renderType_Historico,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import37.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import35.Item(this.parent.parentInjector.get(import38.Form),this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import35.ItemContent();
    this._query_Label_0_0 = new import14.QueryList<any>();
    this._query_Button_0_1 = new import14.QueryList<any>();
    this._query_Icon_0_2 = new import14.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import36.Label(this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_5,'right','');
    this._Label_5_3 = new import36.Label(this.parent.parentInjector.get(import21.Config),new import22.ElementRef(this._el_5),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset([
      this._Label_2_3,
      this._Label_5_3
    ]
    );
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [].concat([
        this._el_2,
        this._el_5
      ]
      ),
      [].concat([
        this._text_1,
        this._text_4,
        this._text_7
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3; }
    if (((token === import36.Label) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Label_5_3; }
    if (((token === import35.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_0_4; }
    if (((token === import35.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'BPM:',this.context.$implicit.bpm,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'Data:',this.context.$implicit.data,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_6,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Historico1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Historico1(viewUtils,parentInjector,declarationEl);
}